AppBundle\Entity\Author:
    type: entity
    table: author
    options:
        comment: "Авторы"
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
            options:
                unsigned: true
    fields:
        fio:
            type: string
            length: 100
            nullable: false
            options:
                comment: "ФИО автора"
    uniqueConstraints:
        fio:
            columns: fio
    manyToMany:
        books:
            targetEntity: Book
            mappedBy: authors